source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.4'

target 'ulak.kurye' do
  use_frameworks!

  pod 'GoogleMaps', '~> 6.2'

  target 'ulak.kuryeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ulak.kuryeUITests' do
    # Pods for testing
  end

end
